version: '3'

services:
  # database
  db:
    image: mariadb
    ports:
      - '8082:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    links:
      - db:db
  web:
   image: php:7.2-apache
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "8080:80"
   links:
     - db
   volumes:
     - ./www:/var/www/html/